### ISSUE TITLE
Error from chokidar (E:\): Error: EBUSY: resource busy or locked, lstat 'E:\DumpStack.log.tmp'

### ISSUE THREAD

**Issue by hqzmss** [qvarts/quill-toggle-fullscreen-button#2]
**Describe the bug**

- Node.js version: v16.18.1
- OS & version: Windows 11
- quill version: 1.3.7
- quill-toggle-fullscreen-button version: 0.1.0

**Actual behavior**
Process crashed. Final log:
`
    ERROR  Failed to compile with 1 error                                                                          14:00:13

This dependency was not found:

quill-toggle-fullscreen-button in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/components/Editor/index.vue?vue&type=script&lang=js&

To install it, you can run: npm install --save quill-toggle-fullscreen-button
Error from chokidar (E:\): Error: EBUSY: resource busy or locked, lstat 'E:\DumpStack.log.tmp'
`

**Comment by qvarts** [comment]
Hi @hqzmss, would you be able to provide more context around what you have done and are trying to accomplish, what command you are running when you see these errors, what your package.json looks like, how your environment is set up, etc.?

Based on what you've reported, I would recommend to check if quill-toggle-fullscreen-button package is in node_modules directory, and if not, install it by run: 

```bash
npm install --save quill-toggle-fullscreen-button
```

For the second error, it looks as if you have something set up incorrectly in the directories you are watching, as in
https://github.com/paulmillr/chokidar/issues/1037

**Comment by David-Coles-Sellr** [comment]
Basically it doesn't install correctly, so when you run it through npm it creates the quill-toggle-fullscreen-button folder, but then it only has 3 files in it
LICENSE-MIT.txt
package.json
README.md
No sub folders are created such as the dist folder that should contain the .js file
