### ISSUE TITLE
Has no dist files

### ISSUE THREAD

**Issue by cereschen** [qvarts/quill-toggle-fullscreen-button#3]
Version 0.1.0
Please check

**Comment by qvarts** [comment]
Hi @cereschen. If you need a packaged version of the source code, you just need to `run npm install && npm run build` to generate the dist folder. Or you can install it from NPM by running `npm install quill-toggle-fullscreen-button`.

**Comment by David-Coles-Sellr** [comment]
I can also concur that when you `npm install quill-toggle-fullscreen-button` it doesn't include the dist folder

**Comment by qvarts** [comment]
Hi @David-Coles-Sellr. I added the dist files to the new release. Check it, please.
